spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/crud_app?allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC"
    username: root
    password: bvx8e2bvx8e2
  main:
    allow-circular-references: true
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  mvc.hiddenmethod.filter.enabled: true

